import { ModeConfig } from '@/types';

export const modes: Record<'governance' | 'devops' | 'full', ModeConfig> = {
    governance: {
        id: 'governance',
        name: 'Processos & Governança',
        accentColor: '#6366F1',
        accentColorHover: '#4F46E5',
        badgeColor: 'bg-indigo-500/10 text-indigo-500',
        description: 'ISO 27001, LGPD, COBIT, RIPD, BPM',
        gradientFrom: '#6366F1',
        gradientTo: '#8B5CF6',
        bgLight: 'bg-indigo-50 dark:bg-indigo-950/30',
        borderLight: 'border-indigo-200 dark:border-indigo-800',
    },
    devops: {
        id: 'devops',
        name: 'DevOps & Cloud',
        accentColor: '#10B981',
        accentColorHover: '#059669',
        badgeColor: 'bg-emerald-500/10 text-emerald-500',
        description: 'Well-Architected, DORA, CIS, DevSecOps, FinOps',
        gradientFrom: '#10B981',
        gradientTo: '#14B8A6',
        bgLight: 'bg-emerald-50 dark:bg-emerald-950/30',
        borderLight: 'border-emerald-200 dark:border-emerald-800',
    },
    full: {
        id: 'full',
        name: 'Full Spectrum',
        accentColor: '#8B5CF6',
        accentColorHover: '#7C3AED',
        badgeColor: 'bg-purple-500/10 text-purple-500',
        description: 'Governança + DevOps & Cloud — Assessment Completo',
        gradientFrom: '#8B5CF6',
        gradientTo: '#C084FC',
        bgLight: 'bg-purple-50 dark:bg-purple-950/30',
        borderLight: 'border-purple-200 dark:border-purple-800',
    },
};